debug: false

logger.level:
  io.pivotal.dmfrey: DEBUG
  org.springframework.web: DEBUG
  com.netflix.feign: DEBUG

server:
  port: ${PORT:8765}

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
